version: '3'
services:
  mouldflow:
    container_name: mouldflow
    build: ./mouldflow
    volumes:
      - ./mouldflow:/mouldflow_app # dev
    networks:
      - docker_network

  nginx:
    container_name: mouldflow_RP
    restart: unless-stopped
    build: ./nginx_conf
    ports:
      - 443:443
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/BEWS005.crt:/etc/nginx/conf/BEWS005.crt
      - ./nginx_conf/BEWS005.key:/etc/nginx/conf/BEWS005.key
    links:
      - mouldflow:mouldflow
    networks:
      - docker_network

  mosquitto:
    container_name: msq_mouldflow
    build: ./mosquitto_conf
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - docker_network
    volumes:
      - ./mosquitto_conf/mosquitto-data:/mosquitto/data
      - ./mosquitto_conf/mosquitto-logs:/mosquitto/logs
      - ./mosquitto_conf/mosquitto-conf:/mosquitto/config
    restart: unless-stopped

networks:
  docker_network:
    driver: bridge





