version: '3'
services:
  mouldflow:
    container_name: mouldflow
    build: ./mouldflow
    volumes:
      - C:/VisualStudioCode/mouldflow/mouldflow:/mouldflow_app # dev
    networks:
      - docker_network

  nginx:
    container_name: mouldflow_RP
    restart: unless-stopped
    build: ./nginx_conf
    ports:
      - 443:443
    volumes:
      - C:/VisualStudioCode/mouldflow/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - C:/VisualStudioCode/mouldflow/nginx_conf/BEWS005.crt:/etc/nginx/conf/BEWS005.crt
      - C:/VisualStudioCode/mouldflow/nginx_conf/BEWS005.key:/etc/nginx/conf/BEWS005.key
    links:
      - mouldflow:mouldflow
    networks:
      - docker_network



networks:
  docker_network:
    driver: bridge





